# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563ccd1f7b572dad675f9cf6bc19e7afbb00403afc8999fc2559722dfb9e9741c4812936587b2091fd5637479be3cdc6702b357d004b9ef576da1b6bf03731b8

test:
  secret_key_base: b64ad665e16fef3a337a9aabdacbab2d1215dc23fbdc4d9c20fcf69816f11dbc08e71dee76cf4d078b3d0b4a5a8e801cb3ad89da3d67f64ff30d68295c050055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
