# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9d6bb4e1a2aed250394c59c91bd30cdeebac76d1ac23b756e93b02fde5b6cad67af9892beb2a0c9c45fd4f5fcc9103c5d36686be1ca0821102d0d26d84db2c

test:
  secret_key_base: 24377ea20fef36fc1725c70e51f8df8e4b016f08078f4e412b3490a8bfb55c7259874980db6accea7da16875cc3e1e0aa3b9f34ef90cd9064d2222f5877d0be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
